### ISSUE TITLE
[1.18.2] Ocean Monument in End Dimension.

### ISSUE THREAD

**Issue by MSandro** [TelepathicGrunt/StructureFloaters-Fabric#1]
Seed: -7156784769461450925
run /execute in minecraft:the_end run tp 155 100 33
you should land on a ocean monument.
They are generating very often.
![image](https://user-images.githubusercontent.com/10937159/166438685-351c2ddb-c7bd-46af-b6cd-cfe6418a9863.png)
![image](https://user-images.githubusercontent.com/10937159/166437910-83e74a91-7a10-4b52-aae6-bd832f2d1158.png)

**Comment by TelepathicGrunt** [comment]
fixed now in v3.0.1. Forgot to add ocean monument's regular biome check after skipping it's hardcoded river/ocean area biome check
